--- 
msg: "working yay"
spring: 
  cloud: 
    gateway: 
      routes: 
        - 
          filters: 
            - "RewritePath=/firstapi/(?<path>.*), /$\\{path}"

          id: firstapi
          predicates: 
            - Path=/firstapi/**
          uri: "lb://firstapi"
        - 
          filters: 
            - "RewritePath=/gateway-kpi/(?<path>.*), /$\\{path}"
          id: gateway-kpi
          predicates: 
            - Path=/proxy/**
          uri: "lb://gateway-kpi"
