--- 
msg: "working yay"
spring: 
  cloud: 
    gateway: 
      routes: 
        - 
          filters: 
            - "RewritePath=/firstapi/(?<path>.*), /$\\{path}"
            - 
              name: RequestRateLimiter
            - 
              args: 
                redis-rate-limiter.burstCapacity: 2
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.requestedTokens: 1
          id: firstapi
          predicates: 
            - Path=/firstapi/**
          uri: "lb://firstapi"
        - 
          filters: 
            - "RewritePath=/gateway-kpi/(?<path>.*), /$\\{path}"
          id: gateway-kpi
          predicates: 
            - Path=/proxy/**
          uri: "lb://gateway-kpi"
